### ISSUE TITLE
docker起動後、ChromeブラウザでURLにアクセスしても映像が表示されない。

### ISSUE THREAD

**Issue by s-muramoto** [nobuo-kobayashi/docker-webrtc-sample#1]
本gitを試させてもらっている者です。

gitのREADME.mdをもとに環境構築をして映像データの出力まで確認しようとしたのですが、
以下のように、データチャネルが作成されないといったエラーが出ており、映像が表示されないようでした。
以下は、どういうケースで起きるエラーがご教示いただけないでしょうか？

実行環境: Ubuntu 18.04 LTS (デスクトップ環境作成済)
試した手順:
0   リモートデスクトップ接続でログイン後、ターミナル起動
①  git clone https://github.com/nobuo-kobayashi/docker-webrtc-sample.git
②  cd docker-webrtc-sample
③  docker-compose build
④  docker-compose up
⑤  上記後、http://<DockerのIP>:9449 にアクセス

Creating signaling ... done
Creating webrtc    ... done
Attaching to signaling, webrtc
signaling    | Listening on port 9449...
webrtc       | > GET / HTTP/1.1
webrtc       | > Soup-Debug-Timestamp: 1658968364
webrtc       | > Soup-Debug: SoupSession 1 (0x55729336b100), SoupMessage 1 (0x55729336f0b0), SoupSocket 1 (0x5572930974d0)
webrtc       | > Host: 127.0.0.1:9449
webrtc       | > Upgrade: websocket
webrtc       | > Connection: Upgrade
webrtc       | > Sec-WebSocket-Key: ny2gO+6el17rV9hM8nNNAg==
webrtc       | > Sec-WebSocket-Version: 13
webrtc       | > Origin: localhost
webrtc       | > Sec-WebSocket-Protocol: 
webrtc       | > Accept-Encoding: gzip, deflate
webrtc       | > User-Agent: gst-webrtc-sample
webrtc       |   
webrtc       | < HTTP/1.1 101 Switching Protocols
webrtc       | < Soup-Debug-Timestamp: 1658968364
webrtc       | < Soup-Debug: SoupMessage 1 (0x55729336f0b0)
webrtc       | < Upgrade: websocket
webrtc       | < Connection: Upgrade
webrtc       | < Sec-WebSocket-Accept: kU/xTqH5kAChtFgQus6pGwR2mMo=
webrtc       |   
signaling    | ws connect...

signaling    | ws connect...
webrtc       | 
**webrtc       | ** (gst-webrtc-sample:1): CRITICAL **: 09:33:15.841: gst_webrtc_bin_create_data_channel: assertion 'webrtc->priv->is_closed != TRUE' failed
webrtc       | Could not create data channel, is usrsctp available?**

**Comment by nobuo-kobayashi** [comment]
gst-webrtc-main.cc の以下のソースコードで、v4l2src device=/dev/video0 を指定しているために、Web カメラを表示するようにしてコミットしていました。

```
void WebRTCMain::startPipeline()
{
  stopPipeline();

  // webrtcbin エレメント名前は固定にしておく必要があります
  // webrtcbin name=webrtcbin を変更する場合には、呼び出している箇所も全て変更する必要があります。
  std::string bin = "webrtcbin name=webrtcbin bundle-policy=max-bundle latency=100 stun-server=stun://stun.l.google.com:19302 \
        v4l2src device=/dev/video0 \
         ! image/jpeg,width=1280,height=720,framerate=30/1 \
         ! jpegdec \
         ! videoconvert \
```

恐らく、Web カメラが参照できていないために、gstreamer が開始できずにいるのだと思います。

```
        v4l2src device=/dev/video0 \
         ! image/jpeg,width=1280,height=720,framerate=30/1 \
         ! jpegdec \
         ! videoconvert \
```

上記の部分を以下のように v4l2src から videotestsrc に変更してみてください。

```
        videotestsrc is-live=true \
         ! videoconvert \
```

修正後に以下のコマンドを再度行なってから、ページにアクセスしてみてください。
docker-compose build
docker-compose up

**Comment by s-muramoto** [comment]
ありがとうございました。無事、動きました。
